<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NfseNacional.PdfGenerator.WinForms</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NfseNacional.PdfGenerator.Lib\NfseNacional.PdfGenerator.Lib.csproj" />
  </ItemGroup>

</Project>
